-- https://devblogs.microsoft.com/azure-sql/change-tracking-in-azure-sql-database/

SELECT COUNT(1) FROM SalesLT.Product;

ALTER DATABASE "sql-db-0408286" SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 5 DAYS, AUTO_CLEANUP = ON); 
ALTER TABLE SalesLT.Product ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);  

SET ROWCOUNT 3;
SELECT ProductID, Name, ListPrice
FROM SalesLT.Product;

DECLARE @LastSyncVersion BIGINT = CHANGE_TRACKING_CURRENT_VERSION();

UPDATE SalesLT.Product
SET ListPrice = 36.99
WHERE ProductID = 707;

SELECT CT.ProductID, CT.SYS_CHANGE_VERSION, CT.SYS_CHANGE_OPERATION
FROM CHANGETABLE(CHANGES SalesLT.Product, @LastSyncVersion) AS CT;   


